server:
  port: 81
rest:
  url:
    prefix: http://PROVIDER-DEPT
spring:
  application:
    name: consumer-feign-dept                        # 对外暴露的微服务名字
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer-dept81   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: microservicecloud
  company.name: com.demo.test
  build.artifactId: $project.artifactId$
  build.version: $project.version$